services:
  backend:
    image: crpi-wmv8qzk3077tt3cn.cn-hangzhou.personal.cr.aliyuncs.com/suchjack/repo-monitor-backend:1.0
    container_name: repo-monitor-backend
    volumes:
      - ./data:/app/backend/data
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    image: crpi-wmv8qzk3077tt3cn.cn-hangzhou.personal.cr.aliyuncs.com/suchjack/repo-monitor-frontend:1.0
    container_name: repo-monitor-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
